from typing import Protocol
from collections.abc import Callable
import numpy as np
import scipy.sparse as sp


class Indexable[T](Protocol):
    def __getitem__(self, key: int, /) -> T: ...
    def __len__(self) -> int: ...

class Indexable2D(Protocol):
    def __getitem__(self, key: tuple[int, int], /) -> bool: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    def nonzero(self) -> tuple[np.ndarray, ...]: ...

class MapLookup(Protocol):
    def __getitem__(self, key: tuple[int, int], /) -> sp.csr_matrix: ...
